language: node_js

sudo: false

node_js:
  - 4.3

# command to install dependencies

# command to run tests
#npm package.json

deploy:
  provider: lambda
  function_name: "$function"
  role: "$role"
  region: "eu-west-1"
  handler_name: "handle"
  access_key_id: "$key_id"
  secret_access_key: "$secret_key"
